### ISSUE TITLE
Game crash on startup due to missing underwater Palette

### ISSUE THREAD

**Issue by PerdGateEnjoyer** [jval1972/Mars3D#3]
![image](https://github.com/jval1972/Mars3D/assets/135927009/4ced83de-7419-4335-ba96-6d58c3545ce9)

AFAIK nothing is wrong with MARS.MAD.Help?

**Comment by jval1972** [comment]
You are using an old version of Mars3D executable (v. 1.0.12.753). You should upgrade to the latest v.1.0.13.755. I suspect you start (GL)Mars3D.exe from a folder different than the executable, that's an issue that it was fixed in the latest release. If not that, make sure that the MARS.MAD file is OK. Due to MARS.MAD size, (GL)Mars3D.exe checks only the lump table for crc32 detection, it does not parse the whole file.

**Comment by PerdGateEnjoyer** [comment]
I got past the underwater palette thing, but now it's saying this.
![image](https://github.com/jval1972/Mars3D/assets/135927009/d8eeef9b-08f9-498b-ba19-e244d9a8bace)
